theme: jekyll-theme-minimal
title: Jolien Cremers
logo: "https://avatars1.githubusercontent.com/u/10900828?s=40&amp;u=f35b4c6d6662132cb6ae10af65a76fcca3b927e1&amp;v=4"
description: Applied statistician bridging the gap between mathematical statistics and applied researchers by bringing new methods to their (potential) users.
