theme: jekyll-theme-minimal
title: Jolien Cremers
logo: "https://avatars0.githubusercontent.com/u/10900828?s=400&u=f35b4c6d6662132cb6ae10af65a76fcca3b927e1&v=4"
description: Applied statistician bridging the gap between mathematical statistics and applied researchers by bringing new methods to their (potential) users.
email: jcre@sund.ku.dk
